### ISSUE TITLE
Cannot read property 'currentlyActive' of undefined

### ISSUE THREAD

**Issue by marigan** [oblador/angular-scroll#99]
When ng model is updated this error appears:

TypeError: Cannot read property 'currentlyActive' of undefined
    at Object.m [as removeSpy] (http://localhost:3333/js/vendor.js:56029:5079)
    at http://localhost:3333/js/vendor.js:56029:7867
    at Scope.$broadcast (http://localhost:3333/js/vendor.js:24047:28)
    at Scope.$destroy (http://localhost:3333/js/vendor.js:23667:14)
    at ngRepeatAction (http://localhost:3333/js/vendor.js:33850:25)
    at Object.$watchCollectionAction [as fn] (http://localhost:3333/js/vendor.js:23437:13)
    at Scope.$digest (http://localhost:3333/js/vendor.js:23570:29)
    at Scope.$apply (http://localhost:3333/js/vendor.js:23833:24)
    at done (http://localhost:3333/js/vendor.js:18991:47)
    at completeRequest (http://localhost:3333/js/vendor.js:19181:7)

**Comment by oblador** [comment]
Closing in lack of response.
